export type WritingMode = "application" | "academic" | "blog" | "work" | "social" | "general";

export type CheckerIssue = {
  code: string;
  severity: "error" | "warning" | "note";
  message: string;
  suggestion: string;
};

export type CheckerResult = {
  ok: boolean;
  mode: WritingMode;
  riskLevel: "low" | "medium" | "high";
  summary: string;
  issues: CheckerIssue[];
  revisionPlan: string[];
  doNotDo: string[];
  privacy: {
    stored: false;
    rawTextLogged: false;
    note: string;
  };
};

const VALID_MODES = new Set<WritingMode>(["application", "academic", "blog", "work", "social", "general"]);

const GENERIC_PHRASES = [
  "in today's fast-paced world",
  "in today's digital landscape",
  "as we navigate",
  "delve into",
  "unlock the potential",
  "it is important to note",
  "plays a crucial role",
  "a testament to",
  "stands as a",
  "i am excited to apply",
  "i am passionate about",
  "dynamic environment",
  "esteemed company",
  "strong fit",
  "leverage my skills",
  "proven track record",
  "uniquely positions me",
  "cutting-edge",
  "game-changing",
  "seamlessly",
  "robust solution"
];

const INTERNAL_PHRASES = [
  "as an ai",
  "candidate evidence record",
  "profile json",
  "source-analysis file",
  "claims in this draft",
  "prompt",
  "generated by ai"
];

const ACADEMIC_WEAKENERS = [
  "clearly proves",
  "undeniably",
  "groundbreaking",
  "revolutionary",
  "this paper will prove",
  "obviously"
];

const ACADEMIC_FORMULAIC_PHRASES = [
  "in this context",
  "this research addresses",
  "critical gap",
  "critical lacuna",
  "paradigm shift",
  "robust predictive framework",
  "strategic priority",
  "macroeconomic stability",
  "macro-financial stability",
  "systemic volatility",
  "intricate interplay",
  "transcending conventional",
  "volatile landscapes",
  "advanced machine learning architectures",
  "high-precision forecasting framework",
  "profound implications",
  "structurally sensitive populations"
];

const POLISHED_TRANSITIONS = ["furthermore", "moreover", "consequently", "therefore", "in conclusion", "historically"];

const ACADEMIC_SPECIFICITY_PATTERNS = [
  /\b\d+(?:\.\d+)?%?\b/i,
  /\bVietnam(?:ese)?\b/i,
  /\bRandom Forest\b/i,
  /\bLightGBM\b/i,
  /\bANN\b|\bArtificial Neural Network/i,
  /\bOLS\b|\bOrdinary Least Squares\b/i,
  /\bSEM\b|\bStructural Equation Modeling\b/i,
  /\bPrice Perception\b|\bPRI\b/i,
  /\bcross-sectional\b/i,
  /\bbinar(?:y|ized|isation|ization)\b|\bbinary outcome\b/i,
  /\bhouseholds?\b/i,
  /\bsample\b/i,
  /\bdataset\b/i
];

const ACADEMIC_LIMITATION_PATTERNS = [
  /\bdoes not prove\b/i,
  /\bnot prove\b/i,
  /\bshould be interpreted (?:carefully|with caution)\b/i,
  /\bcross-sectional\b/i,
  /\bself-reported\b/i,
  /\bbinary outcome\b/i,
  /\bbinar(?:y|ized|isation|ization)\b/i,
  /\blimit(?:ed|ation|ations)?\b/i,
  /\bcannot show\b/i,
  /\bdoes not mean\b/i,
  /\bconstrained by\b/i
];

const PRACTICAL_USER_PATTERNS = [
  /\bhouseholds?\b/i,
  /\bfamil(?:y|ies)\b/i,
  /\bfinancial institutions?\b/i,
  /\blocal governments?\b/i,
  /\bpolicy\b|\bpolicymakers?\b/i,
  /\bbanks?\b/i,
  /\bconsumers?\b/i,
  /\bcommunities\b|\bcommunity\b/i
];

const HUMAN_TEXTURE_PATTERNS = [
  /\bI noticed\b/i,
  /\bwhat changed\b/i,
  /\bwhat went wrong\b/i,
  /\btrade[- ]?off\b/i,
  /\bconstraint\b/i,
  /\btested\b/i,
  /\bmeasured\b/i,
  /\bbuilt\b/i,
  /\bfixed\b/i,
  /\bfailed\b|\bfailure\b/i,
  /\btime\b|\bday\b|\bweek\b|\bmonth\b/i,
  /\b\d+(?:\.\d+)?%?\b/i
];

const APPLICATION_TEMPLATE_PHRASES = [
  "please accept my application",
  "i am applying for",
  "i am writing to apply",
  "i wanted to apply for",
  "my strongest related experience",
  "my strongest match",
  "this experience fits",
  "this is why the",
  "the role interests me",
  "the role feels relevant",
  "this role is especially relevant",
  "across business analysis",
  "across previous roles",
  "i have often worked where",
  "that has made me comfortable",
  "i have built a strong foundation",
  "i believe i can contribute",
  "thank you for reviewing my application",
  "thank you for considering my application",
  "i would be glad to discuss",
  "i would welcome the opportunity",
  "could support your team"
];

const APPLICATION_EVIDENCE_TEXTURE_PATTERNS = [
  /\b\d{4}\b/i,
  /\b\d+(?:\.\d+)?%?\b/i,
  /\btesting\b|\btested\b|\bverification\b|\bvalidated\b/i,
  /\bmissing\b|\bfailed\b|\bissue\b|\bproblem\b|\bgap\b/i,
  /\bcolleagues?\b|\bsupport teams?\b|\bstakeholders?\b|\busers?\b/i,
  /\bsource tables?\b|\bdata flows?\b|\blogic\b|\bobjects?\b/i,
  /\bJira\b|\bSAP\b|\bPower BI\b|\bExcel\b|\bConfluence\b/i,
  /\battached\b|\bdocument\b|\bprovide\b|\breview\b|\bfollow[- ]?up\b/i
];

const APPLICATION_PERSONAL_ANCHOR_PATTERNS = [
  /\bI was new\b/i,
  /\bI had to learn\b/i,
  /\bI learned\b/i,
  /\bI noticed\b/i,
  /\bI worked through\b/i,
  /\bI compared\b/i,
  /\bI traced\b/i,
  /\bI can bring\b/i,
  /\bI authored\b/i,
  /\bI mapped\b/i,
  /\bI coordinated\b/i,
  /\bI supported\b/i,
  /\bmy work was to\b/i,
  /\bone useful part of my work\b/i,
  /\bthat trained me\b/i,
  /\bthe useful part was\b/i,
  /\bfrom the beginning\b/i,
  /\bnot from a pure\b/i
];

const APPLICATION_DIFFICULTY_PATTERNS = [
  /\bhard\b|\bdifficult\b|\bunclear\b|\bmissing\b|\bgap\b|\bissue\b|\bproblem\b/i,
  /\bconstraint\b|\btrade[- ]?off\b|\bchanged\b|\bnot only\b|\bstill\b/i,
  /\btesting\b|\bchecked\b|\breview(?:ed)?\b|\bchallenge(?:d)?\b/i,
  /\blearn(?:ed)?\b|\btaught me\b|\btrained me\b|\bmade .* concrete\b/i
];

const APPLICATION_ARTIFACT_PATTERNS = [
  /\buser stories?\b|\bacceptance criteria\b|\bprocess diagrams?\b|\bworkflow documents?\b/i,
  /\bguide(?:s)?\b|\bhow[- ]tos?\b|\bslide decks?\b|\bpresentations?\b|\bmeeting materials?\b/i,
  /\bwikis?\b|\bproject boards?\b|\bnotes?\b|\bhandovers?\b|\breport(?:s|ing)?\b/i,
  /\bdocumentation\b|\bshared material\b|\bworking documents?\b|\bsource tables?\b|\bdata flows?\b/i,
  /\bmaster[- ]data\b|\bevaluations?\b|\banalys(?:is|es)\b|\bpublic writing\b|\bwritten material\b/i
];

const APPLICATION_UNSUPPORTED_STRENGTH_WORDS = [
  /\bnative\b/i,
  /\bfluent\b/i,
  /\bexpert\b/i,
  /\bsenior\b/i,
  /\blead(?:ing)?\b/i,
  /\bworld[- ]class\b/i,
  /\bproven track record\b/i
];

const APPLICATION_ABSTRACT_NOUNS = [
  "implementation",
  "coordination",
  "communication",
  "documentation",
  "organization",
  "stakeholders",
  "environment",
  "foundation",
  "contribution",
  "execution",
  "alignment",
  "discipline"
];

function normalizeText(text: string): string {
  return text.replace(/\s+/g, " ").trim();
}

function applicationBody(rawText: string): string {
  const normalized = rawText.replace(/\r\n/g, "\n");
  const salutation = normalized.match(/\bDear [^\n,]+,/i);
  if (!salutation) return rawText;
  const afterSalutation = normalized.slice(salutation.index ?? 0);
  const close = afterSalutation.search(/\n\s*(Best regards|Kind regards|Sincerely),?/i);
  return close >= 0 ? afterSalutation.slice(0, close) : afterSalutation;
}

function splitParagraphs(rawText: string): string[] {
  return rawText
    .split(/\n\s*\n/)
    .map((paragraph) => paragraph.trim())
    .filter(Boolean);
}

function splitSentences(text: string): string[] {
  return normalizeText(text)
    .split(/(?<=[.!?])\s+/)
    .map((sentence) => sentence.trim())
    .filter(Boolean);
}

function wordCount(text: string): number {
  return (normalizeText(text).match(/[A-Za-zÀ-ỹ0-9']+/g) ?? []).length;
}

function sentenceLengths(sentences: string[]): number[] {
  return sentences.map((sentence) => wordCount(sentence));
}

function average(values: number[]): number {
  if (!values.length) return 0;
  return values.reduce((sum, item) => sum + item, 0) / values.length;
}

function standardDeviation(values: number[]): number {
  if (values.length < 2) return 0;
  const mean = average(values);
  const variance = average(values.map((item) => (item - mean) ** 2));
  return Math.sqrt(variance);
}

function repeatedStarts(sentences: string[]): string[] {
  const counts = new Map<string, number>();
  for (const sentence of sentences) {
    const match = sentence.match(/^\s*([A-Za-z']+)/);
    if (!match) continue;
    const key = match[1].toLowerCase();
    counts.set(key, (counts.get(key) ?? 0) + 1);
  }
  return [...counts.entries()]
    .filter(([word, count]) => count >= 3 && ["i", "the", "this", "my", "it", "we"].includes(word))
    .map(([word, count]) => `${word}=${count}`);
}

function countMatches(lowered: string, phrases: string[]): string[] {
  return phrases.filter((phrase) => lowered.includes(phrase));
}

function countPatternHits(text: string, patterns: RegExp[]): number {
  return patterns.reduce((count, pattern) => count + (pattern.test(text) ? 1 : 0), 0);
}

function countOccurrences(text: string, pattern: RegExp): number {
  return text.match(pattern)?.length ?? 0;
}

function abstractNounRatio(lowered: string, totalWords: number): number {
  if (!totalWords) return 0;
  const hits = APPLICATION_ABSTRACT_NOUNS.reduce((count, noun) => {
    return count + countOccurrences(lowered, new RegExp(`\\b${noun}s?\\b`, "g"));
  }, 0);
  return hits / totalWords;
}

function listLineRatio(rawText: string): number {
  const lines = rawText
    .split(/\n/)
    .map((line) => line.trim())
    .filter(Boolean);
  if (!lines.length) return 0;
  const listLines = lines.filter((line) => /^([-*]|\d+[.)])\s+/.test(line)).length;
  return listLines / lines.length;
}

function paragraphStartCounts(paragraphs: string[]): Map<string, number> {
  const counts = new Map<string, number>();
  for (const paragraph of paragraphs) {
    const firstSentence = splitSentences(paragraph)[0] ?? paragraph;
    const normalized = firstSentence.toLowerCase();
    const match =
      normalized.match(/^(dear|please|i am|i'm|my|this|that|the|thank you|best regards)\b/) ??
      normalized.match(/^([a-z']+)/);
    if (!match) continue;
    const key = match[1];
    counts.set(key, (counts.get(key) ?? 0) + 1);
  }
  return counts;
}

function addIssue(issues: CheckerIssue[], issue: CheckerIssue): void {
  issues.push(issue);
}

export function parseWritingMode(mode: string | undefined): WritingMode {
  const normalized = String(mode || "general").toLowerCase().trim() as WritingMode;
  return VALID_MODES.has(normalized) ? normalized : "general";
}

export function checkWritingHumanFit(input: {
  text: string;
  mode?: string;
  audience?: string;
  purpose?: string;
}): CheckerResult {
  const mode = parseWritingMode(input.mode);
  const rawText = input.text || "";
  const auditableRawText = mode === "application" ? applicationBody(rawText) : rawText;
  const text = normalizeText(auditableRawText);
  const lowered = text.toLowerCase();
  const sentences = splitSentences(text);
  const lengths = sentenceLengths(sentences);
  const paragraphs = splitParagraphs(auditableRawText);
  const issues: CheckerIssue[] = [];
  const totalWords = wordCount(text);

  if (totalWords < 40) {
    addIssue(issues, {
      code: "too_short",
      severity: "warning",
      message: "The text is too short for a reliable voice or reader check.",
      suggestion: "Send a complete paragraph or section so the checker can evaluate rhythm, claims, and reader value."
    });
  }

  for (const phrase of countMatches(lowered, INTERNAL_PHRASES)) {
    addIssue(issues, {
      code: "internal_language",
      severity: "error",
      message: `The text contains internal or AI-system language: "${phrase}".`,
      suggestion: "Replace it with reader-facing wording, or remove it completely."
    });
  }

  for (const phrase of countMatches(lowered, GENERIC_PHRASES)) {
    addIssue(issues, {
      code: "generic_ai_phrase",
      severity: "warning",
      message: `The phrase "${phrase}" can make the writing feel generic or machine-polished.`,
      suggestion: "Replace it with a concrete reason, example, source, task, or observed problem."
    });
  }

  const repeats = repeatedStarts(sentences);
  if (repeats.length) {
    addIssue(issues, {
      code: "repeated_sentence_starts",
      severity: "warning",
      message: `Several sentences start the same way: ${repeats.join(", ")}.`,
      suggestion: "Vary the sentence entry points by starting from context, evidence, reader need, limitation, or result."
    });
  }

  if (lengths.length >= 5) {
    const sentenceAverage = average(lengths);
    const spread = Math.max(...lengths) - Math.min(...lengths);
    const deviation = standardDeviation(lengths);
    if (sentenceAverage >= 14 && sentenceAverage <= 26 && (spread <= 8 || deviation < 6)) {
      addIssue(issues, {
        code: "too_even_rhythm",
        severity: "warning",
        message: "The sentence rhythm is very even, which can read like generated prose.",
        suggestion: "Let the structure follow the idea: mix one short sentence with longer explanation where the logic needs it."
      });
    }
    if (sentenceAverage > 30) {
      addIssue(issues, {
        code: "long_average_sentence",
        severity: "warning",
        message: `The average sentence length is high (${sentenceAverage.toFixed(1)} words), which can make the prose feel inflated and detector-prone.`,
        suggestion: "Split the densest claims into shorter method, evidence, and interpretation sentences."
      });
    }
  }

  if (paragraphs.length >= 3) {
    const paragraphLengths = paragraphs.map((paragraph) => wordCount(paragraph)).filter((count) => count > 0);
    const paragraphAverage = average(paragraphLengths);
    if (paragraphAverage > 0 && standardDeviation(paragraphLengths) / paragraphAverage < 0.22) {
      addIssue(issues, {
        code: "paragraph_symmetry",
        severity: "warning",
        message: "The paragraphs are nearly the same size, which can create a mechanically balanced draft.",
        suggestion: "Let paragraph size follow purpose: one short framing paragraph, one evidence paragraph, and one limitation or implication paragraph."
      });
    }
  }

  if (/[,;][^.!?]+,[^.!?]+,[^.!?]+,[^.!?]+/.test(text)) {
    addIssue(issues, {
      code: "list_like_sentence",
      severity: "warning",
      message: "At least one sentence reads like a long list of keywords.",
      suggestion: "Turn the list into one evidence-backed example or split it into a clearer reader-facing sentence."
    });
  }

  if (/[—–]/.test(text)) {
    addIssue(issues, {
      code: "decorative_dash",
      severity: "note",
      message: "The text uses long dash punctuation.",
      suggestion: "Use a comma, period, colon, or simpler sentence unless the dash is genuinely needed by the style."
    });
  }

  if (/\b[A-Za-z]+-[A-Za-z]+-[A-Za-z]+\b/.test(text)) {
    addIssue(issues, {
      code: "decorative_hyphen_chain",
      severity: "note",
      message: "The text contains a multi-part hyphen chain.",
      suggestion: "Keep fixed terms, but rewrite decorative compounds into simpler language."
    });
  }

  if (mode === "application") {
    if (!/\b(role|position|team|work|project|requirement|company|mission|posting)\b/i.test(text)) {
      addIssue(issues, {
        code: "missing_role_trigger",
        severity: "warning",
        message: "The application text does not show a clear role-specific trigger.",
        suggestion: "Add the exact part of the role, work, or team context that caused the application."
      });
    }
    if (!/\b(project|worked|built|analyzed|mapped|documented|tested|supported|coordinated|created)\b/i.test(text)) {
      addIssue(issues, {
        code: "missing_candidate_evidence",
        severity: "warning",
        message: "The application text has weak evidence texture.",
        suggestion: "Use one real project, task, workflow, tool, or situation from the candidate's local evidence."
      });
    }
    const templateHits = countMatches(lowered, APPLICATION_TEMPLATE_PHRASES);
    for (const phrase of templateHits.slice(0, 6)) {
      addIssue(issues, {
        code: "application_template_phrase",
        severity: "warning",
        message: `The phrase "${phrase}" is a common cover-letter template signal.`,
        suggestion: "Replace it with a specific reason, real project moment, document/action detail, or reader-facing contribution."
      });
    }
    if (templateHits.length >= 3) {
      addIssue(issues, {
        code: "application_template_sequence",
        severity: "warning",
        message: `The letter contains ${templateHits.length} template-like cover-letter moves.`,
        suggestion: "Break the predictable opening-evidence-fit-closing skeleton. Start from the actual job task and one concrete experience detail."
      });
    }
    if (/^Dear Hiring Team,\s*(Please accept my application|I am (writing to apply|applying for))/i.test(text)) {
      addIssue(issues, {
        code: "generic_application_opening",
        severity: "warning",
        message: "The opening starts with a standard application formula.",
        suggestion: "Open with the concrete job task or situation that made the role worth applying for, then name the role."
      });
    }
    const paragraphStarts = paragraphStartCounts(paragraphs);
    const repeatedParagraphStarts = [...paragraphStarts.entries()].filter(
      ([start, count]) => count >= 2 && ["i am", "my", "this", "that", "the"].includes(start)
    );
    if (repeatedParagraphStarts.length) {
      addIssue(issues, {
        code: "application_paragraph_skeleton",
        severity: "warning",
        message: `Several paragraphs begin with predictable cover-letter anchors: ${repeatedParagraphStarts
          .map(([start, count]) => `${start}=${count}`)
          .join(", ")}.`,
        suggestion: "Vary paragraph movement: job trigger, concrete task, difficulty, result, and practical contribution."
      });
    }
    if (totalWords >= 150 && countPatternHits(text, APPLICATION_EVIDENCE_TEXTURE_PATTERNS) < 4) {
      addIssue(issues, {
        code: "thin_application_evidence_texture",
        severity: "warning",
        message: "The letter has limited real work texture for its length.",
        suggestion: "Add concrete task evidence such as a year, tool, document, test, issue, stakeholder, data flow, or reviewed output."
      });
    }
    if (totalWords >= 150 && countPatternHits(text, APPLICATION_PERSONAL_ANCHOR_PATTERNS) < 2) {
      addIssue(issues, {
        code: "missing_personal_work_anchor",
        severity: "warning",
        message: "The letter has weak signs of a real person working through a specific situation.",
        suggestion: "Add one modest first-person work detail: what was hard, what you checked, what you learned, or what you helped clarify."
      });
    }
    if (totalWords >= 150 && countPatternHits(text, APPLICATION_DIFFICULTY_PATTERNS) < 2) {
      addIssue(issues, {
        code: "missing_work_difficulty",
        severity: "warning",
        message: "The letter does not show enough real work friction, checking, learning, or constraint.",
        suggestion: "Add one concrete difficulty: what was unclear, what needed checking, what was missing, or what the work taught you."
      });
    }
    if (totalWords >= 150 && countPatternHits(text, APPLICATION_ARTIFACT_PATTERNS) < 2) {
      addIssue(issues, {
        code: "missing_checked_artifact",
        severity: "warning",
        message: "The letter does not name enough concrete work artifacts.",
        suggestion: "Name the artifact or output: user story, acceptance criteria, guide, report, workflow note, source table, deck, wiki, or handover."
      });
    }
    if (totalWords >= 170 && abstractNounRatio(lowered, totalWords) > 0.055) {
      addIssue(issues, {
        code: "abstract_application_language",
        severity: "warning",
        message: "The letter leans heavily on abstract application nouns instead of concrete work moments.",
        suggestion: "Replace abstract fit language with a specific task, artifact, reviewer, issue, or result."
      });
    }
    for (const pattern of APPLICATION_UNSUPPORTED_STRENGTH_WORDS) {
      const match = text.match(pattern);
      if (!match) continue;
      addIssue(issues, {
        code: "unsupported_strength_word",
        severity: "warning",
        message: `The word "${match[0]}" can overstate capability in an application unless the local profile proves it.`,
        suggestion: "Use a more bounded claim, or attach evidence from the profile before keeping the wording."
      });
      break;
    }
    if (/\bgood documentation is not decoration\b/i.test(text)) {
      addIssue(issues, {
        code: "slogan_like_application_line",
        severity: "warning",
        message: "The letter contains a slogan-like sentence that can read as polished AI copy.",
        suggestion: "Replace the slogan with a concrete example of documentation helping testing, review, handover, or team follow-up."
      });
    }
  }

  if (mode === "academic") {
    for (const phrase of countMatches(lowered, ACADEMIC_WEAKENERS)) {
      addIssue(issues, {
        code: "academic_overclaim",
        severity: "warning",
        message: `The phrase "${phrase}" may overstate the academic claim.`,
        suggestion: "Use cautious academic framing and connect the claim to method, evidence, or limitation."
      });
    }
    if (!/\b(study|research|evidence|method|data|finding|literature|limitation|sample|model|analysis)\b/i.test(text)) {
      addIssue(issues, {
        code: "missing_academic_anchor",
        severity: "warning",
        message: "The academic text lacks visible research anchors.",
        suggestion: "Add method, evidence, literature, data, limitation, or scope language as appropriate."
      });
    }
    for (const phrase of countMatches(lowered, ACADEMIC_FORMULAIC_PHRASES)) {
      addIssue(issues, {
        code: "academic_formulaic_phrase",
        severity: "warning",
        message: `The phrase "${phrase}" is a common polished-academic signal in this project profile.`,
        suggestion: "Replace it with a precise method, variable, result, dataset detail, or scoped claim."
      });
    }
    const transitionHits = POLISHED_TRANSITIONS.reduce(
      (count, phrase) => count + countOccurrences(lowered, new RegExp(`\\b${phrase}\\b`, "g")),
      0
    );
    if (transitionHits >= 3) {
      addIssue(issues, {
        code: "too_many_polished_transitions",
        severity: "warning",
        message: `The text uses ${transitionHits} formal transition markers, which can make the argument feel template-driven.`,
        suggestion: "Keep only transitions that clarify logic. Let some sentences connect through evidence instead of connector words."
      });
    }
    if (totalWords >= 120 && countPatternHits(text, ACADEMIC_SPECIFICITY_PATTERNS) < 3) {
      addIssue(issues, {
        code: "missing_academic_specificity",
        severity: "warning",
        message: "The academic section has too little concrete research texture for its length.",
        suggestion: "Add the dataset size, setting, variables, model names, outcome definition, or measured result."
      });
    }
    if (totalWords >= 120 && countPatternHits(text, ACADEMIC_LIMITATION_PATTERNS) === 0) {
      addIssue(issues, {
        code: "missing_limitation_boundary",
        severity: "warning",
        message: "The academic claim does not visibly state a limitation or interpretation boundary.",
        suggestion: "Add what the design can and cannot support, such as survey limits, cross-sectional scope, or measurement constraints."
      });
    }
    if (totalWords >= 120 && countPatternHits(text, PRACTICAL_USER_PATTERNS) === 0) {
      addIssue(issues, {
        code: "missing_practical_user",
        severity: "warning",
        message: "The text does not clearly connect the finding to a practical reader or affected group.",
        suggestion: "Name the users, households, institutions, policymakers, or communities affected by the result."
      });
    }
    const thisStarts = sentences.filter((sentence) => /^this\b/i.test(sentence)).length;
    if (sentences.length >= 5 && thisStarts / sentences.length > 0.35) {
      addIssue(issues, {
        code: "high_this_sentence_ratio",
        severity: "warning",
        message: "Too many sentences start from 'This', which can make academic prose sound generated.",
        suggestion: "Start some sentences from the method, sample, variable, limitation, or implication instead."
      });
    }
  }

  if ((mode === "blog" || mode === "social") && totalWords >= 80 && !/[?]/.test(text)) {
    addIssue(issues, {
      code: mode === "blog" ? "flat_blog_voice" : "flat_social_voice",
      severity: "note",
      message: "The text has little visible curiosity or reader interaction.",
      suggestion: "Add a real trigger, question, friction point, or moment of uncertainty if it fits the topic."
    });
  }

  if ((mode === "blog" || mode === "social" || mode === "work") && totalWords >= 80) {
    if (countPatternHits(text, HUMAN_TEXTURE_PATTERNS) < 2) {
      addIssue(issues, {
        code: "missing_human_texture",
        severity: "warning",
        message: "The writing has weak evidence of lived context, measured work, friction, or tradeoff.",
        suggestion: "Add one concrete trigger, measured result, constraint, mistake, tradeoff, or observed reader problem."
      });
    }
    if (listLineRatio(rawText) > 0.45) {
      addIssue(issues, {
        code: "over_structured_list_shape",
        severity: "warning",
        message: "Most of the section is list-shaped, which can feel like an agent-generated framework.",
        suggestion: "Convert the most important list item into a short human example, then keep only the useful bullets."
      });
    }
  }

  const hardFailures = issues.filter((issue) => issue.severity === "error").length;
  const warnings = issues.filter((issue) => issue.severity === "warning").length;
  const riskBoostCodes = new Set([
    "academic_formulaic_phrase",
    "application_template_phrase",
    "application_template_sequence",
    "application_paragraph_skeleton",
    "generic_application_opening",
    "thin_application_evidence_texture",
    "missing_personal_work_anchor",
    "missing_work_difficulty",
    "missing_checked_artifact",
    "abstract_application_language",
    "unsupported_strength_word",
    "slogan_like_application_line",
    "long_average_sentence",
    "missing_academic_specificity",
    "missing_limitation_boundary",
    "paragraph_symmetry",
    "too_many_polished_transitions",
    "missing_human_texture"
  ]);
  const boostedWarnings = issues.filter((issue) => riskBoostCodes.has(issue.code)).length;
  const riskLevel =
    hardFailures > 0 || warnings >= 5 || boostedWarnings >= 3
      ? "high"
      : warnings >= 2 || boostedWarnings >= 1
        ? "medium"
        : "low";

  return {
    ok: hardFailures === 0,
    mode,
    riskLevel,
    summary:
      riskLevel === "low"
        ? "The writing is usable. Review the notes, then revise only where the feedback improves reader trust."
        : riskLevel === "medium"
          ? "The writing has some generic or mechanically polished signals. Revise the highlighted areas before final use."
          : "The writing needs revision before final use. Fix errors first, then reduce generic rhythm and unsupported claims.",
    issues,
    revisionPlan: buildRevisionPlan(mode, issues),
    doNotDo: [
      "Do not add fake stories, fake metrics, or deliberate grammar mistakes.",
      "Do not copy another person's tone or private examples.",
      "Do not treat any detector score as proof of authorship.",
      "Do not weaken factual or academic correctness just to sound casual."
    ],
    privacy: {
      stored: false,
      rawTextLogged: false,
      note: "The checker processes submitted text transiently and returns feedback. Raw submitted text is not persisted by this service."
    }
  };
}

function buildRevisionPlan(mode: WritingMode, issues: CheckerIssue[]): string[] {
  const plan = ["Fix any error-level issues first."];
  if (issues.some((issue) => issue.code === "generic_ai_phrase")) {
    plan.push("Replace generic phrases with a specific trigger, source, task, example, or limitation.");
  }
  if (issues.some((issue) => issue.code === "too_even_rhythm" || issue.code === "repeated_sentence_starts")) {
    plan.push("Vary sentence starts and sentence length where the logic naturally changes.");
  }
  if (issues.some((issue) => issue.code === "long_average_sentence" || issue.code === "paragraph_symmetry")) {
    plan.push("Break the polished block shape: split dense claims and let paragraph length follow purpose.");
  }
  if (issues.some((issue) => issue.code === "missing_human_texture")) {
    plan.push("Add human texture: a trigger, measured result, constraint, failure, tradeoff, or reader problem.");
  }
  if (mode === "application") {
    plan.push("Make the fit concrete: role signal, candidate evidence, practical contribution.");
    if (
      issues.some((issue) =>
        [
          "application_template_phrase",
          "application_template_sequence",
          "application_paragraph_skeleton",
          "generic_application_opening",
          "thin_application_evidence_texture",
          "missing_personal_work_anchor",
          "missing_work_difficulty",
          "missing_checked_artifact",
          "abstract_application_language",
          "unsupported_strength_word",
          "slogan_like_application_line"
        ].includes(issue.code)
      )
    ) {
      plan.push("Rewrite away from cover-letter skeleton language: use the job task, a real work difficulty, a checked artifact, and a modest contribution.");
    }
  } else if (mode === "academic") {
    plan.push("Make the claim academically safer: research anchor, evidence, scope, and limitation.");
    if (
      issues.some((issue) =>
        [
          "academic_formulaic_phrase",
          "missing_academic_specificity",
          "missing_limitation_boundary",
          "missing_practical_user",
          "too_many_polished_transitions"
        ].includes(issue.code)
      )
    ) {
      plan.push("Replace polished academic packaging with exact variables, sample details, method boundaries, and practical users.");
    }
  } else if (mode === "blog") {
    plan.push("Recover the human trigger: why this topic matters, what went wrong, and what changed your thinking.");
  } else if (mode === "work") {
    plan.push("Keep the reader's action clear: context, decision, blocker, next step.");
  } else if (mode === "social") {
    plan.push("Sharpen the hook, keep one useful idea, and remove inflated creator-style language.");
  }
  plan.push("Run the checker again only on the revised section, not the whole private workspace.");
  return [...new Set(plan)];
}
